Homework2
Sutrow/MIPT_homework pull request #3
Opened 2023-09-25 11:43 UTC by Sutrow

update

2023-10-16 14:34 UTC, KozlovAV426 requested changes

2023-10-16 14:34 UTC, KozlovAV426 commented on src/IntHolder.java
> +    // Конструктор
можно не помечать комментариями то, что очевидно))

2023-10-16 14:34 UTC, KozlovAV426 commented on src/Methods.java
> +        return str.equals(reversedStr.toString());
пройтись линейно и проверить, без лишний аллокаций в виде toLowerCase и разворота строки

2023-10-28 11:37 UTC, ASemenovng requested changes

2023-10-28 11:37 UTC, ASemenovng commented on src/IntHolder.java
> +    // Методы для арифметических операций
арифметика не должна возвращать новый объект каждый раз, нужно менять состояние текущего объекта, иначе ты будешь создавать кучу ненужных промежуточных объектов

2023-10-28 11:37 UTC, ASemenovng commented on src/Point.java
> +    public static void main(String[] args) {
метод main лучше делать отдельно (в своем классе) от твоих классов

2023-10-28 11:37 UTC, ASemenovng commented on src/Car.java
> +    public static void main(String[] args) {
аналогично про main

2023-10-28 11:37 UTC, ASemenovng commented on src/Pet.java
> +    public static class Cat extends Pet {
все эти классы наследники не должны быть вложенными - это отдельные классы, которые должны быть в отдельном файле, аналогично про FoodType

2023-10-28 11:37 UTC, ASemenovng commented on src/Pet.java
> +    public static void main(String[] args) {
аналогично про main (дальше писать про это не буду, поправь везде это)

2023-10-28 11:37 UTC, ASemenovng commented on src/Task7.java
> +    public static class Engine {
1. это можно в целом было сделать и в файле Car.java
2. ну и реализовать все таки нужно полностью) Как минимум пустой класс `Engine` - это странно)
3. Также Engine не нужно делать static, у тебя предполагается, что двигатель отдельно от машины мы создавать не хотим, а сейчас так сделать можно. Поэтому лучше сделать `Engine` не статиком, а в билдер передавать не `new Engine()`,  а параметры (поля) этого класса, т.е. расход топлива и вкл/выкл. А создавать объект Engine уже в конструкторе Car, тогда не будет проблем со статик контекстом

2023-10-28 11:37 UTC, ASemenovng commented on src/Main.java
> +public class Main {
вот это как раз и нужно сделать отдельно)

2023-10-28 11:37 UTC, ASemenovng commented on src/Main.java
> +sealed class Shape permits Ball, Cylinder, Pyramid {
для каждого класса свой файл - если речь не идет про внутренние классы (тут у тебя файл Main.java, который внутри содержит помимо Main еще классы Shape и все остальное, супер неочевидно, где лежат эти файлы и почему так)

2023-12-01 16:45 UTC, merged